### ISSUE TITLE
Document logging syntax

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/ZConfig#10]
IMO, the best way to configure Python logging is with ZConfig, but it's not documented and thus a best-kept secret.

It would be great if this got documented.

**Comment by jamadden** [comment]
There is one example, but it's buried pretty deep (fourth level in the ToC): http://zconfig.readthedocs.io/en/latest/standard-components.html#using-the-logging-components

**Comment by freddrake** [comment]
Sadly, that example only uses ``eventlog`` and not ``logger`` sections.  ``eventlog`` isn't that meaningful a name in many applications.

**Comment by jamadden** [comment]
And without looking up the schema .xml files, I have no idea what the actual sections and keys can be. 

A Sphinx extension that could process the schemas and output docs would be awesome. 😄

**Comment by mgedmin** [comment]
Here's an example I had lying around

```xml
    <logger>
      name zc.tracelog
      propagate false
      <logfile>
        format %(message)s
        path var/log/trace.log
      </logfile>
    </logger>
```

**Comment by jamadden** [comment]
There is actually a second small example right in the README.rst, which means it shows up prominently on PyPI, but sadly not on RTD.

**Comment by jimfulton** [comment]
Yes, I did that.  Of course, at the time, the docs weren't in ReST.  I added this in desperation. :)

**Comment by jamadden** [comment]
Slowly coming closer, at least for reference-type docs. See https://github.com/zopefoundation/ZConfig/pull/24#issuecomment-281832190
