### ISSUE TITLE
Fix pyroma and check-manifest

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/ZConfig#32]
Both produce minor warnings:
```
$ pyroma -a .
------------------------------
Checking .
Found ZConfig
------------------------------
Your package does not have keywords data.
------------------------------
Final rating: 9/10
Cottage Cheese
------------------------------
```

And 
```
$ check-manifest
lists of files in version control and sdist do not match!
missing from sdist:
  .coveragerc
  .readthedocs.yml
  doc/root-and-child-config.conf
  doc/simple-root-config.conf
suggested MANIFEST.in rules:
  include *.yml
  include .coveragerc
  recursive-include doc *.conf
```

**Comment by jamadden** [comment]
The change note about `ZConfig.sphinx` should also link to  [the docs]( https://zconfig.readthedocs.io/en/latest/documenting-components.html#documenting-components) and probably [the PR](https://github.com/zopefoundation/ZConfig/pull/25).

**Comment by freddrake** [comment]
Keywords data?

(Never heard of pyroma.)

**Comment by jamadden** [comment]
The `keywords='foo bar baz'` line in setup.py, which here, is missing. It facilitates searching and categorization. At least theoretically.

Pyroma's pretty neat, it catches a lot of small common things.

**Comment by jamadden** [comment]
I took a pass at keywords in #33.

**Comment by jamadden** [comment]
([pyroma](https://pypi.python.org/pypi/pyroma) is one of the two tools that [zest.releaser](https://pypi.python.org/pypi/zest.releaser) offers to run during a release, defaulting to aborting the release if it doesn't pass. Guess what the other tool is  😄 )
