### ISSUE TITLE
Test test_no_schema fails with ArgumentTypeError, not SystemExit

### ISSUE THREAD

**Issue by adisbladis** [zopefoundation/ZConfig#34]
Running tests on 3.2.0 yields this:
```
======================================================================
ERROR: test_no_schema (ZConfig.tests.test_schema2html.TestSchema2HTML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adisbladis/sauce/ZConfig/ZConfig/tests/test_schema2html.py", line 79, in test_no_schema
    run_transform)
  File "/nix/store/wz55g27gm5jna37a2m33hi801p04n33a-python-2.7.13/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/adisbladis/sauce/ZConfig/ZConfig/tests/test_schema2html.py", line 63, in run_transform
    schema2html.main(args)
  File "/home/adisbladis/sauce/ZConfig/ZConfig/schema2html.py", line 135, in main
    schema = load_schema(args.schema, args.package, args.package_file)
  File "/home/adisbladis/sauce/ZConfig/ZConfig/_schema_utils.py", line 305, in load_schema
    schema_reader = argparse.FileType('r')(schema)
  File "/nix/store/wz55g27gm5jna37a2m33hi801p04n33a-python-2.7.13/lib/python2.7/argparse.py", line 1142, in __call__
    raise ArgumentTypeError(message % (string, e))
ArgumentTypeError: can't open 'test': [Errno 2] No such file or directory: 'test'
```

Either https://github.com/zopefoundation/ZConfig/blob/3.2.0/ZConfig/schema2html.py#L135 or https://github.com/zopefoundation/ZConfig/blob/3.2.0/ZConfig/_schema_utils.py#L305 needs to handle ArugemntTypeError and do exit()

**Comment by tseaver** [comment]
Thanks for the report.  Unfortunately, I cannot reproduce the test failure:

```bash
$ git clone https://github.com/zopefoundation/ZConfig
Cloning into 'ZConfig'...
remote: Counting objects: 3274, done.
remote: Total 3274 (delta 0), reused 0 (delta 0), pack-reused 3274
Receiving objects: 100% (3274/3274), 5.25 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (1982/1982), done.
Checking connectivity... done.
$ cd ZConfig/
$ git checkout 3.2.0
Note: checking out '3.2.0'.
...
HEAD is now at 34701e6... Preparing release 3.2.0
$ tox
...
___________________________________ summary ____________________________________
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  pypy: commands succeeded
  congratulations :)
```

How are you running the tests?

**Comment by mgedmin** [comment]
The failing test (`test_schema`) is very simple:

```
    def test_no_schema(self):
        self.assertRaises(SystemExit,
                          run_transform)
```

`run_transform` is defined as `def run_transform(*args)` and invokes `schema2html.main(args)`.

`main(argv=None)` begins as follows:

```
def main(argv=None):
    argv = argv or sys.argv[1:]
```

and so this test actually looks at the `sys.argv` of the test runner invocation.  I doubt that's intentional.

**Comment by mgedmin** [comment]
@adisbladis I'm curious if changing the first line of `main()` in schame2html.py to

```
argv = argv if argv is not None else sys.argv[1:]
```

fixes your error?

(I also have no idea how to reproduce the failure you're seeing and so cannot test that myself.)

**Comment by mgedmin** [comment]
@jamadden: git blame tells me you touched that test last -- can you tell me what the test was intended to test?  AFAICT if you don't specify a schema (or any command-line arguments) the script will try to read from stdin -- won't that make the test block waiting for user interaction? 

AFAICT currently it works because you get an error about an unknown command-line argument because sys.argv is `['nosetests', '--with-xunit', '--with-xcoverage']` when one runs `tox`.

**Comment by jamadden** [comment]
> I doubt that's intentional.

Yup, not intentional. An oversight on my part, albeit in my defense one that’s easy to make if tests are consistently run in one particular way.

**Comment by jamadden** [comment]
> can you tell me what the test was intended to test?

It’s been awhile, and I suspect the implementation has changed since I added that test (probably by me). But basically I think it was intended to help achieve full coverage in an older version of the code. It’s not immediately clear to me what it achieves now.

**Comment by mgedmin** [comment]
Ok, that gives us an approach: delete the test, fix main() not to fall back to sys.argv when the passed args is an empty tuple (or list for that matter), then check for coverage regressions and write new tests to cover those.
