### ISSUE TITLE
Release 3.3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZConfig#43]
I'd like to have a release of version 3.3.

I can do it myself if I (`icemac`)  get the necessary PyPI rights.

**Comment by freddrake** [comment]
ZConfig 3.3.0 landed on PyPI yesterday.

**Comment by icemac** [comment]
Right, but the Changes.rst here on Github claim that it is unreleased.
Maybe only a `git push` is missing,.

**Comment by icemac** [comment]
Okay, it only ended up on the wrong branch, see #44 to fix this.

**Comment by jamadden** [comment]
Sorry about that!
