### ISSUE TITLE
zope.conf / wsgi.conf lost ability to refer to environment parameters (ZConfig)

### ISSUE THREAD

**Issue by mcgfeller** [zopefoundation/ZConfig#76]
In Zope 2, I could include environment parameters in zope.conf using the `$name` syntax. This seems to be no longer working in Zope 4 (ZConfig 3.0).

Adding  `defines = os.environ` when `defines is None` to class `ZConfig.Loader.ConfigLoader._parse_resource()` restores this, but I'm not sure whether this would be the best place: 

```
    def _parse_resource(self, matcher, resource, defines=None):
        if defines is None:
            defines = os.environ
        parser = ZConfig.cfgparser.ZConfigParser(resource, self, defines)
        parser.parse(matcher)
```
Thanks and best regards,
Martin

**Comment by dataflake** [comment]
This seems to be a ZConfig issue rather than a Zope issue

**Comment by freddrake** [comment]
You should be able to refer to environment variables using `$(name)` syntax in values.

@mcgfeller: What version of ZConfig are you using that isn't doing this?

**Comment by mcgfeller** [comment]
@freddrake : ZConfig is 3.5.0, which came with Zope 4.5.1. 

The `$(name)` syntax works - it seems somewhere along (ancient) history, the `()` where added _or_ the environment was no longer passed into ZConfig, so I have to put the `()` into my old config file. 

Thanks a lot to all who have helped, but foremost to @freddrake, who solved it for me.

Feeling grateful - and a bit embarrassed for not being able to find it in the source (near miss is still miss).

**Comment by freddrake** [comment]
Glad I could help, @mcgfeller!
